DELETE FROM SYS_USER;
INSERT INTO SYS_USER VALUES ('003428','朱家昇','ROLE_AP');
INSERT INTO SYS_USER VALUES ('003815','黃蘅','ROLE_AP');

DELETE FROM　FUNCTION;
INSERT INTO FUNCTION VALUES (1,0,'保會','');
INSERT INTO FUNCTION VALUES (2,0,'費會','');
INSERT INTO FUNCTION VALUES (3,1,'保會報表1','/pol/report1');
INSERT INTO FUNCTION VALUES (4,1,'保會報表2','/pol/report2');
INSERT INTO FUNCTION VALUES (5,2,'費會報表1','/exp/report1');

DELETE FROM ROLE_FUNCTION;
INSERT INTO ROLE_FUNCTION VALUES ('ROLE_AP',1);
INSERT INTO ROLE_FUNCTION VALUES ('ROLE_AP',2);
INSERT INTO ROLE_FUNCTION VALUES ('ROLE_AP',3);
INSERT INTO ROLE_FUNCTION VALUES ('ROLE_AP',4);
INSERT INTO ROLE_FUNCTION VALUES ('ROLE_AP',5);