DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER (
	ID VARCHAR(10) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	ROLE VARCHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS FUNCTION;
CREATE TABLE FUNCTION (
	ID INT NOT NULL,
	PARENT_ID INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS ROLE_FUNCTION;
CREATE TABLE ROLE_FUNCTION (
	ROLE VARCHAR(20) NOT NULL,
	FUNCTION_ID INT NOT NULL,
	PRIMARY KEY (ROLE,FUNCTION_ID)
);